#!/usr/bin/env bash
# Installing  n configurg HAproxy on server
apt-get update
apt-get install -y haproxy

cat <<EOL >> /etc/haproxy/haproxy.cfg
frontend myfrontend
  bind *:80
  default_backend myservers

backend myservers
  balance roundrobin
  server 397719-web-01 3.84.158.197:80
  server 397719-web-02 54.90.60.108:80
EOL
service haproxy start
