#!/usr/bin/env bash
# Display login name, uid, and home directory for each account in /etc/passwd

while IFS=':' read -r login _ uid _ _ home _
do
    printf '%s:%s:%s\n' "${login}" "${uid}" "${home}"
done </etc/passwd
