#!/usr/bin/env bash
# Displays Best School and then Hi on a new line

c=1
while [ $c -le 10 ]
do
	if [ $c -eq 9 ]
	then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	c=$((c + 1))
done
