#!/usr/bin/env bash
#Displays numbers from 1 to 20

y="1"
while [ $y -le 20 ]
do
	case $y in
		4)
			echo "$y"
			echo "bad luck from China"
			;;
		9)
			echo "y"
			echo "bad luck from Japan"
			;;
		17)
			echo "$y"
			echo "bad luck from Italy"
			;;
		*)
			echo "$y"
	esac
	((y++))
done
